"""sync_model_schema

Revision ID: 80420dd65062
Revises: 9bf371e0120c
Create Date: 2026-10-03 14:25:13.947584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80420dd65062'
down_revision: Union[str, Sequence[str], None] = '9bf371e0120c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_uploads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('iv_hex', sa.String(length=64), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('copies_authorized', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_uploads_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_uploads_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('os_info', sa.String(length=255), nullable=False, server_default='Windows 11 Pro'))
        batch_op.add_column(sa.Column('app_version', sa.String(length=64), nullable=False, server_default='1.0.0'))
        batch_op.add_column(sa.Column('auth_state', sa.String(length=32), nullable=False, server_default='AUTHENTICATED'))
        batch_op.add_column(sa.Column('api_key_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='ONLINE'))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_print_jobs_idempotency_key'), ['idempotency_key'], unique=False)

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('connection_info', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='READY'))
        batch_op.add_column(sa.Column('supported_paper_sizes', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nonce', sa.String(length=64), nullable=False, server_default=''))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=False, server_default='ACTIVE'))
        batch_op.create_index(batch_op.f('ix_shops_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shops_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('nonce')

    with op.batch_alter_table('printers', schema=None) as batch_op:
        batch_op.drop_column('supported_paper_sizes')
        batch_op.drop_column('status')
        batch_op.drop_column('connection_info')
        batch_op.drop_column('driver_name')

    with op.batch_alter_table('print_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_jobs_idempotency_key'))
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('status')
        batch_op.drop_column('api_key_hash')
        batch_op.drop_column('auth_state')
        batch_op.drop_column('app_version')
        batch_op.drop_column('os_info')

    with op.batch_alter_table('pending_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_uploads_user_id'))
        batch_op.drop_index(batch_op.f('ix_pending_uploads_session_id'))

    op.drop_table('pending_uploads')
    # ### end Alembic commands ###
